name: Deploy DHIS2

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      DB_NAME:
        description: 'Database name'
        required: true
      DB_USER:
        description: 'Database user'
        required: true
      DB_PASSWORD:
        description: 'Database password'
        required: true
      DB_PORT:
        description: 'Database port'
        required: true
        default: '5432'
      DHIS2_VERSION:
        description: 'DHIS2 version'
        required: true
      DOMAIN_NAME:
        description: 'Domain name'
        required: true
      SERVER_IP:
        description: 'Server IP'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      id: ssh-setup
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Add remote server to known hosts
      run: |
        ssh-keyscan ${{ github.event.inputs.SERVER_IP || secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy DHIS2
      env:
        DB_NAME: ${{ github.event.inputs.DB_NAME || secrets.DB_NAME }}
        DB_USER: ${{ github.event.inputs.DB_USER || secrets.DB_USER }}
        DB_PASSWORD: ${{ github.event.inputs.DB_PASSWORD || secrets.DB_PASSWORD }}
        DB_PORT: ${{ github.event.inputs.DB_PORT || secrets.DB_PORT }}
        DHIS2_VERSION: ${{ github.event.inputs.DHIS2_VERSION || secrets.DHIS2_VERSION }}
        DOMAIN_NAME: ${{ github.event.inputs.DOMAIN_NAME || secrets.DOMAIN_NAME }}
        SERVER_IP: ${{ github.event.inputs.SERVER_IP || secrets.SERVER_IP }}
      run: |
        scp dhis2_install.sh root@${{ env.SERVER_IP }}:/tmp/
        ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << 'EOF'
          export DB_NAME=${DB_NAME}
          export DB_USER=${DB_USER}
          export DB_PASSWORD=${DB_PASSWORD}
          export DB_PORT=${DB_PORT}
          export DHIS2_VERSION=${DHIS2_VERSION}
          export DOMAIN_NAME=${DOMAIN_NAME}
          bash /tmp/dhis2_install.sh
        EOF
